# conda environment configuration for mybinder
name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - python=3.9
  - adjustText
  - cartopy
  - gdal
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - metpy
  - numpy
  - owslib
  - pandas
  - Pillow
  - plotly
  - tabulate
  - pip
  - pip:
    - adjustText
    - matplotlib
    - metpy
    - owslib
    - pandas
    - Pillow
    - tabulate
