# conda environment configuration for mybinder
name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - python=3.9
  - adjusttext=0.7.3.1
  - cartopy
  - gdal
  - ipyleaflet
  - ipympl
  - ipywidgets
  - matplotlib
  - metpy
  - numpy
  - owslib
  - pandas
  - Pillow
  - plotly
  - tabulate
  - pip
  - pip:
      - matplotlib
      - owslib
      - pandas
      - Pillow
      - tabulate
